name: dart_application_1
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
http: ^1.2.2

dev_dependencies:
  http: ^1.2.2
  lints: ^3.0.0
  test: ^1.24.0
